<?php
/**
 * *******************************************************
 * Author: Manish Giri
 * Copyright: Mobiotics IT Solution Private Limited
 * Version: 1.0
 * Date: 03-Aug-2015
 * FileName: errorcodes.php
 * Description: Error Code Definition File
 * ********************************************************
 */
$GLOBALS['errorcodes'] = array (
		1001=>"DB Error",
		1002=>"Redis Connection Error",
		1003=>"Invalid LCO",
		1004=>"Invalid Username or Password",
		1005=>"OTP Verification Not Completed",
		1006=>"LCO Has Not Registered",
		1007=>"LCO Already Registered",
		1008=>"Could Not Send SMS",
		1009=>"OTP Pin Mismatch",
		1010=>"Lco Does Not Have Previlege",
		1011=>"Could Not Send Mail",
		1012=>"No Data To Update",
		1013=>"Invalid Data Provided",
		1013=>"FR code mismatch",
		1014=>"No Such Data",
		1015=>"Lco Is Not Registered To SMS",
		1016=>"OTP Generation Failed",
		1017=>"Duplicate Entry",
		1018=>"Lco Registration Failed",
		1019=>"OTP Verification Pending",
		1020=>"Mobile Number already exist",
		1021=>"Email already exist",
		1022=>"No Data Found",
		1023=>"Create Customer Failed",
		1024=>"Create Sandbox Failed",
		1025=>"Get Device Failed",
		1026=>"Product Listing Failed",
		1027=>"Invalid Agreement Id",
		1028=>"Address Listing Failed",
		1029=>"Customer Listing By Business Role Failed",
		1030=>"Get Customer Failed",
		1031=>"Authentication Failed",
		1032=>"Invalid Serial Number",
		1033=>"Customer Insertion Failed",
		1034=>"Customer Updation Failed",
		1035=>"Document Insertion Failed",
		1036=>"Document Updation Failed",
		1037=>"Device Insertion Failed",
		1038=>"Device Updation Failed",
		1039=>"Activation Insertion Failed",
		1040=>"Activation Updation Failed",
		1041=>"KYC Creation Failed",
		1042=>"KYC File Upload Failed",
		1043=>"KYC Updation Failed",
		1044=>"NO KYC For Customer",
		1045=>"Get Customer Kyc Status Failed",
		1046=>"Wrong Birthdate Format",
		1047=>"Already Subscribed Device Serial Number",
		1048=>"Customer Already Subscribed With This Mobile Number",
		1049=>"Customer Already Subscribed With This Email",
		1050=>"Invalid Email Format",
		1051=>"Invalid Mobile Number Format",
		1052=>"User already exist in system",
		1053=>"Update Plan Failed",
		1054=>"KYC Already Verified / Failed",
		1055=>"Invalid or Inactive Customer",
		1056=>"Publish Queue Failed",
		1057=>"Disconnect Failed",
		1058=>"Reconnect Failed",
		1059=>"List Product Faield",
		1060=>"Get Product Detail Failed",
		1061=>"List Customers Failed",
		1062=>"List Product Agreement Detail Failed",
		1063=>"Invalid Product Agreement Id",
		1064=>"Failed TO Execute Device Command",
		1065=>"Customer Update Failed",
		1066=>"Product Subscription Failed",
		1067=>"Document Listing Failed",
		1068=>"Sandbox Finalize Failed",
		1069=>"Quote is not generated for this plan. Please contact help desk",
		1070=>"Create Conditional Voucher Failed",
		1071=>"Nothing To Change",
		1072=>"Failed To Get Lco Address",
		1073=>"Please Enter Valid Pincode",
		1074=>"Invalid Product",
		1075=>"Failed To Get Customer Details",
		1076=>"This Device Not Applicable For This LCO",
		1077=>"Serial Number Not Applicable",
		1078=>"No Quote Id To Activate Product",
		1079=>"Listing Ticket Categories Failed",
		1080=>"Ticket Generation Failed",
		1081=>"Ticket Listing Failed",
		1082=>"System Error Occured",
		1083=>"Listing Ticket Contact Methods Failed",
		1084=>"Getting Customer Parent Detail Failed",
		1085=>"Reconnect Product Failed",
		1086=>"KYC Not Verified",
		1087=>"Try Renew Within 15 days of expiry",
		1088=>"Get Device Id From Customer Id Failed",
		1089=>"Invalid Customer Id/Serial no",
		1090=>"Validity Expired",
		1091=>"Product Is Not Disconnected",
		1092=>"Validity Is Not Expired. Please Use Reconnect",
		1093=>"No Product Available To Subscribe",
		1094=>"No Product Available To Renew",
		1095=>"No Product Available To Disconnect",
		1096=>"No Product Available To Reconnect",
		1097=>"No Active Base Packs/hardware",
		1098=>"Insufficient Credit",
		1099=>"MSO Debit Initiate Failed",
		2000=>"Missing Parameter",
		2001=>"Create Plan Failed",
		2002=>"Getting Product Type Failed",
		2003=>"Invalid Producttypeid/Producttypename",
		2004=>"Invalid LCO Type",
		2005=>"MSO Should Be Registered For NONGIL LCO",
		2006=>"Bulk Retrack Failed",
		2007=>"No File Exist",
		2008=>"No KYC Document Found",
		2009=>"Activation Already Initiated For This Product",
		2010=>"Curl Exception",
		2011=>"Get Device Failed",
		2012=>"Invalid Product Type",
		2013=>"Customer Listing Failed",
		2014=>"Make Payment Failed",
		2015=>"Payment Reversal Failed",
		2016=>"Reset Password Failed",
		2017=>"Request Timeout",
		2018=>"Invalid Token",
		2019=>"Bad Request",
		2020=>"Bulk Report Insertion Failed",
		2021=>"Please Upload Documents",
		2022=>"Missing Productlist",
		2023=>"Product Renewal Failed",
		2024=>"Failed To Get Financial Details",
		2025=>"Retrack request for this ID is already processed. Please try after some time.",
		2026=>"Don't Renewal Failed",
		2027=>"Regenerating Quote Invoice Failed",
		2028=>"Invalid Product Status",
		2029=>"Product Already Subscribed",
		2030=>"Product Not Yet Subscribed",
		2031=>"Mismatch Productid With Contractid",
		2040=>"Failed To Get Quote",
		2041=>"Don't exceed the file length more than 5000",
		2042=>"Try Don't Renew Within 15 days of expiry",
		2043=>"Data deletion Failed",
		2044=>"Old device belongs to other lco, you can not swap this device",
		2045=>"Invalid Old serial number for swap",
		2046=>"New device belongs to other lco, you can not swap this device",
		2047=>"Invalid New serial number for swap",
		2048=>"Customer already has a Active Basepack",
		2049=>"Invalid Template Id",
		2050=>"OSD request for this ID is already processed. Please try after some time.",
		2051=>"WLMSO is not allowed to Register",
		2052=>"Close ticket failed",
		2053=>"No update",
		2054=>"Copy To NAS Failed",

		2054=>"Failed to update LCO's status",
		2055=>"Failed to update LCO",
		2056=>"New limit should not be same as current limit",
		2057=>"Product already in disconnected status",

		2058=>"Insufficient funds in LCO Wallet financial account",
		2059=>"Invalid type for getting total price",
		2060=>"Failed to get LCO wallet Balance",
		2061=>"No pending plans for activation",
		2062=>"LCO Mismatch",
		2063=>"Can't credit money to inactive LCO",
		2064=>"Subuser exists with this username",
		2065=>"Insufficient funds in MSO Wallet financial account, Please contact your MSO",
		2066=>"This Plans Can't be Activated here",

		2070=>"Invalid First Name/Surname. First 2 character should be alphabets",
		2071=>"Invalid Surname. First 2 character should be alphabets",
		2074=>"Invalid Box Type",
		2075=>"Quantity should be more than or equal to 500 for this box type",

		//autorenew Errors
		2076=>"Invalid plan for scheduling autorenew",
		2077=>"Customer is already scheduled for autorenew",
		2078=>"Renew period should be 1 to 12 months",
		2079=>"Please provide valid renew period (3,6 or 12)",
		2080=>"No data to update",
		2081=>"Invalid customer/Serial number",
		2082=>"Invalid status provided",
		2083=>"Customer Scheduled for Autorenew, Please Inactive the autorenew to proceed further.",
		2084=>"Invalid Tag Provided",
		2085=>"You can't update the status of this customer",
		2086=>"This is Scheme customer, you can not Schedule this customer.",
		2087=>"This customer is already active, you can not schedule more than once.",
		2088=>"For this customer base pack details is not available .",
		2089=>"Customer is Scheduled for Change basepack, So he is not allowed to schedule for autorenew.",

		//Change base pack
		2090=>"Current base pack is Disconnected/Expired. New base pack cannot be scheduled for change base pack.",
		2091=>"Create Preactivation failed.",
		2092=>"Change base pack already scheduled",
		2093=>"Same Base pack cannot be scheduled for change base pack",
		2094=>"Customer's Product status is not Scheduled.",
		2095=>"Customer is Scheduled by ADMIN.",

		//Payment Errors
		3000=>"Something went wrong with payment servers.",
		3001=>"Missing Transaction Id",
		3002=>"This payment transaction is invalid without transaction reference.",
		3003=>"Payment Not Found",
		3004=>"Payment Successfully Processed",
		3005=>"Payment Canceled By User",
		3006=>"Payments do not tally",
		3007=>"Invalid User",
		3008=>"Payment Failed",
		3009=>"Payment Update Failed",
		3010=>"Add amount to credit/ update payment failed",
		3011=>"Transaction Mismatch",
		3012=>"Payment Already Processed",
		3013=>"Data Tampered",
		3014=>"Invalid Entitype",
		3015=>"Payment Initiate Failed",
		3016=>"Payment Failed. Please try again",
		3017=>"Transaction under process, please try after some time",
		3018=>"Tried maximum time for this payment id",
		3019=>"Invalid Prefix",

		//MSO related
		4001=>"MSO Has Not Registered",
		4002=>"Invalid MSO",
		4003=>"MSO already exist in system",
		4004=>"MSO Registration Failed",
		4005=>"MSO Already Registered",
		4006=>"MSO Updation Failed",
		4007=>"Merchant Details Updation is pending",
		4008=>"MSO is Inactive",
		4009=>"MSO Mismatch",
		4010=>"Invalid data provided",
		4011=>"Amount is greater than transferlimit",
		4012=>"Amount should be greater than zero.",

		//Citrus payment related
		6001=>"Transaction failure",
		6002=>"User Dropped",
		6003=>"CANCELED",
		6004=>"FORWARDED",
		6005=>"PG_FORWARD_FAIL",
		6006=>"INQUIRY_STATUS_FAILED",
		6007=>"SESSION_EXPIRED",
		6008=>"REFUND_INITIATED",
		6009=>"REFUND_FORWARDED",
		6010=>"REFUND_PROCESS",
		6011=>"REFUND_SUCCESS",
		6012=>"REFUND_FAILED",
		6013=>"DEBIT_REQ_SENT",
		6014=>"SUCCESS_ON_VERIFICATION",
		6015=>"PG_REJECTED",
		6016=>"REVERSED",
		6017=>"ON_HOLD",
		6018=>"Payment Failed",

		6019=>"Data tampered",

		100000=>"No File Found",

		700000=>"Plan not eligible for renew, as validity is more than 15 days",

		//Customer Related
		5002=>"Customer Already Registered",
		5003=>"Customer Registration Failed",
		5004=>"Customer status is Pending",
		5005=>"Customer is not Registered",
		5006=>"Failed to get Balance",
		5007=>"Invalid customer entity type",

		//CRF related
		7001=>"User already exists",
		7002=>"Invalid Address Proof",
		7003=>"Invalid ID Proof",
		7004=>"Invalid Residence",
		7005=>"Invalid Payment Mode",
		7006=>"Invalid Subscriber Category",
		7007=>"Failed to get Table Name",
		7009=>"Invalid Mso",

		8000=>"You can renew this plan after 31st October 2017",
		//TPSL Error Codes
		8001=>"Get Token Failed",

		//PAYTM related errors
		9000=>"Checksum error",
		9001=>"Payment is in pending state please check after 20 minutes.",
		9002=>"Transaction is in progress. Please check it after sometime.",

		//Mysql Related

		10001=>"Failed to connect Mysql connection",

		//dpo releated

		11001=>"Invalid Class for create",
		11002=>"Invalid type for Customer",
		11003=>"Failed to get DP entities",
		11004=>"DP entity mismatch",
		11005=>"Invalid customertypeid",
		11006=>"Unable to distribute funds. The funds are insufficient for this quote",
		11007=>"Postapid bill is not yet paid for this customer. So he can't activate any plans",
		11008=>"Customer doesn't have enough balance to activate these plans",
		11009=>"OutStanding amoun is zero",
		11010=>"Wallet balance is lessthan outstanding amount",
		11011=>"You can't pay morethan outstanding amount",
		11012=>"Contract id is missing",
		11013=>"Prepaid Customer can not renew active plans",
		11014=>"Invalid Initiator",
		11015=>"Failed to get DpoEntity",
		11016=>"Failed to pay bill",
		11017=>"Invalid DP customer, please enter valid DP customer id",
		11018=>"DPO Entity can't register, Please register with DPO Username",
		11019=>"Dpo Entity does not belongs to DPO user",
		11020=>"Customer does not belongs to this user",
		11021=>'Retrieving LCO payment stat Failed',
		11022=>'Retrieving LCO Renew stat Failed',

		//DP Selfcare

		12001=>"No active product found",
		12002=>"Requested product is expired, please renew your expired product",
		12003=>"From date or To date cannot be greater than expiry date",
		12004=>"Failed to send email to your DPO, please try again after sometime",
		12005=>"Plan is already requested for the Disconnect",
		12006=>"Plan is already requested for the Reconnect",
		12007=>"Change back is already requested.",

		//Suspension
		13001=>"Customer can't suspend with current basepack product Id.",
		13002=>"Invalid activity type",
		13003=>"Customer in suspended state, please reactivate it.",
		13004=>"Suspension failed, please try again.",
		13005=>"Reactivate failed, please try again.",
		13006=>"Device suspension initiate failed.",
		13007=>"Customer status is not in Suspended state.",
		13008=>"Device reactivation data not found",
		13009=>"Customer is not in suspended state.",

		//Add financial Account
		130010=>"Failed to Add Financial Account",
		130011=>"Failed to get Financial Account",

		// masking error
		130012=>"This product is masked for renew till 25th of September 2018",
		130013=>"Attention Business Partners :- Due to migration of customers onto NTO packages with effect from 1st Feb 19 we are disabling the Advance renewal of old packages with immediate effect. You will be able to start activating new customer NTO packages from 01st February. The new NTO packages will be released in a few days on the portals.",

		130014=>"No Slab Details for this, please contact support team for more details",
		130015=>"Failed to get CreateConditionalVoucherCharges Result",

		//cancel product
		2096=>"No Product Available to Cancel",
		2097=>"Cancel Product Failed",
		
		//Charge Period releated
		15000 => "Invalid Charge Period",
		
		//Cart related
		15001 => "Failed to data to cart",
		15002 => "Invalid data",
		15003 => "Empty Cart",
		15004 => "Only 15 products can be added to cart",
		15005 => "Missing parameters",
		
		//promo Related
		16001 => "No Promo ads exists",
		16002 => "File Format is wrong",
		16003 => "Failed to get Data",
		16004 => "Invalid Portal type provided",
		
		//STB Return Related
		
		16010 => "Failed to return STB",
		16011 => "Base pack is Active, so can't return the STB",
		16012 => "No STB found for this customer",
		16013 => "STB is NOT active, so can't return",
		
		//Dynamic OSD
		
		16020 => "Failed to Send OSD",
		
		//Subuser releate
		
		17001 => "You cant create subser with the master username",
		17002 => "Subuser you are trying to add does not belong to you",
		17003 => "Some error occured!!! Please try again",
		
		2098 => "Failed to get document from s3",

		17004 => "Bulk OSD Failed",
		2099 => "Entered mobile number is not valid.Please enter the registered mobile number",

		//mere apne error codes
		17005 => "Encryption mismatch in LCO authorization",
		17006 => "Failed to generate JWT token",
		17007 => "Partnerdetails already exists",
		17008 => " Mismatch",
		17009 => "Customer is not LCO customer",
		17010 => "This third party initiator dosent exist in our system",
		17011 => "No active plans found",
		
		
		
);

		
?>
